with-expecter: true
filename: "{{.InterfaceName}}.go"
dir: "{{.InterfaceDir}}/internal/mocks"
mockname: "{{.InterfaceName}}"
outpkg: "mocks"
packages:
  github.com/clambin/pinger/pkg/ping:
    interfaces:
      Socket:
