FROM python:3.7.1

LABEL Author="Christophe Lambin"
LABEL E-mail="christophe.lambin@gmail.com"
LABEL version="0.0.2"

ENV HOSTS "localhost"

RUN mkdir /app
WORKDIR /app

COPY *.py Pip* /app/

RUN apt-get update && \
    apt-get install net-tools
RUN pip install --upgrade pip && \
    pip install pipenv && \
    pipenv install --dev --system --deploy --ignore-pipfile

EXPOSE 8080

CMD python pinger.py
