apiVersion: apps/v1
kind: Deployment
metadata:
  name: pinger
  namespace: default
  labels:
    app: pinger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pinger
  template:
    metadata:
      labels:
        app: pinger
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      containers:
      - name: collector
        image: clambin/pinger:develop
        imagePullPolicy: Always
        env:
        - name: HOSTS
          valueFrom:
            configMapKeyRef:
              name: collector-config
              key: hosts
        args:
        - --interval=5
#        - --debug