name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  test:
    uses: clambin/workflows/.github/workflows/test.yaml@main
  build:
    needs:
      - test
    uses: clambin/workflows/.github/workflows/build.yaml@main
    with:
      target: pinger
  release:
    needs:
      - build
    uses: clambin/workflows/.github/workflows/release.yaml@main

