name: Test

on:
  push:
    branches-ignore:
      - master
      - slog
  pull_request_target:
    branches:
      - master

jobs:
  test:
    uses: clambin/workflows/.github/workflows/test.yaml@main
