name: Test

on:
  push:
    branches-ignore:
      - master
      - labels
  pull_request_target:
    branches:
      - master

jobs:
  test:
    uses: clambin/workflows/.github/workflows/test.yaml@main
    secrets:
      codecov-token: ${{ secrets.CODECOV_TOKEN }}
