name: Python package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --dev
    - name: Lint with flake8
      run: |
        pipenv run flake8 --max-line-length 120
    - name: SAST
      run: |
        pipenv run safety check
        pipenv run bandit -r -x ./tests .
    - name: Test with pytest
      run: |
        pipenv run pipenv run pytest --cov=. --cov-report=xml
    - name: Upload codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
